# face_keys_wl.py — keyboard face, v2: real KeyV2 keycaps, Work-Louder flavour.
#
# The caps are NOT hand-modelled here: keycap_wl.stl is generated by the
# open-source KeyV2 parametric keycap library (rsheldiii/KeyV2) via OpenSCAD,
# then imported. Profile is tuned to Work Louder's Creator/Codex look: uniform
# height, chunky, generous plan corner radii, gentle taper, near-flat top with a
# whisper of spherical dish.
#
# Mounting follows Work Louder too: caps float above a dark recessed keywell
# floor with tight gaps, rather than sitting in individual chiclet apertures.
#
#   /Applications/Blender.app/Contents/MacOS/Blender --background --python face_keys_wl.py

import bpy
import bmesh
import math
from mathutils import Vector

OUT_DIR = "/Users/stefanlenoach/Code/world-radio/case"
S = 0.001

# ---- parameters (mm) ----
PLATE = 110.0
PT = 6.0            # face plate thickness
CAP = 29.0          # cap base size we want on this face
GAP = 1.3           # gap between cap bases — tight
PITCH = CAP + GAP   # 28.5
WELL_MARGIN = 2.2   # dark floor visible around the cap field
WELL_DEPTH = 4.0    # recess depth
CAP_LIFT = 1.3      # cap bottom above the well floor
CAP_Z_SCALE = 1.0  # keep height sane while widening the cap

# KeyV2 source cap footprint (see keycap_wl.scad)
SRC_CAP = 18.3


def mm(v):
    return v * S


def clean_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()
    for block in (bpy.data.meshes, bpy.data.materials, bpy.data.lights, bpy.data.cameras):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def _bool(target, other, op):
    mod = target.modifiers.new(name="bool", type="BOOLEAN")
    mod.operation = op
    mod.object = other
    mod.solver = "EXACT"
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(other, do_unlink=True)


def boolean(target, cutter):
    _bool(target, cutter, "DIFFERENCE")


def union(target, other):
    _bool(target, other, "UNION")


def bevel(ob, width_mm, segments=6, angle_limit=60):
    mod = ob.modifiers.new(name="bevel", type="BEVEL")
    mod.width = mm(width_mm)
    mod.segments = segments
    mod.limit_method = "ANGLE"
    mod.angle_limit = math.radians(angle_limit)
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.modifier_apply(modifier=mod.name)


def smooth(ob, angle=0.55):
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.context.view_layer.objects.active = ob
    try:
        bpy.ops.object.shade_auto_smooth(angle=angle)
    except Exception:
        bpy.ops.object.shade_smooth()


def satin(name, color, rough=0.38, coat=True):
    """Satin injection-moulded plastic: slight clearcoat + micro texture."""
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    bsdf = nt.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Roughness"].default_value = rough
    if coat and "Coat Weight" in bsdf.inputs:
        bsdf.inputs["Coat Weight"].default_value = 0.25
        bsdf.inputs["Coat Roughness"].default_value = 0.22
    noise = nt.nodes.new("ShaderNodeTexNoise")
    noise.inputs["Scale"].default_value = 1400.0
    noise.inputs["Detail"].default_value = 3.0
    bump = nt.nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.010
    nt.links.new(noise.outputs["Fac"], bump.inputs["Height"])
    nt.links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return m


def assign(ob, mat):
    ob.data.materials.clear()
    ob.data.materials.append(mat)


def import_cap():
    """Import the KeyV2-generated cap and normalise it to origin/base-at-zero."""
    path = f"{OUT_DIR}/keycap_wl.stl"
    before = set(bpy.data.objects)
    try:
        bpy.ops.wm.stl_import(filepath=path)
    except Exception:
        bpy.ops.import_mesh.stl(filepath=path)
    new = list(set(bpy.data.objects) - before)
    ob = new[0]
    ob.name = "CapSrc"
    # KeyV2 exports in mm; Blender imports 1 unit = 1 mm -> scale to metres
    ob.scale = (S, S, S)
    bpy.ops.object.transform_apply(scale=True)
    # sit base at z=0, centre in plan
    bpy.context.view_layer.objects.active = ob
    bpy.ops.object.select_all(action="DESELECT")
    ob.select_set(True)
    bpy.ops.object.origin_set(type="ORIGIN_GEOMETRY", center="BOUNDS")
    bb = [ob.matrix_world @ Vector(c) for c in ob.bound_box]
    zmin = min(v.z for v in bb)
    ob.location = (0, 0, -zmin)
    bpy.ops.object.transform_apply(location=True)
    return ob


def build():
    clean_scene()

    cream = satin("Deck", (0.878, 0.842, 0.762), rough=0.42)
    keymat = satin("Keycap", (0.925, 0.905, 0.858), rough=0.30)  # brighter than deck
    dark = satin("WellPlate", (0.014, 0.015, 0.017), rough=0.78, coat=False)

    centers = [(-PITCH + c * PITCH, -PITCH + r * PITCH) for r in range(3) for c in range(3)]
    field = 2 * PITCH + CAP  # 84
    well = field + 2 * WELL_MARGIN  # 90

    # ---- face plate with a recessed keywell ----
    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, mm(PT / 2)))
    plate = bpy.context.object
    plate.name = "KeyFace"
    plate.scale = (mm(PLATE), mm(PLATE), mm(PT))
    bpy.ops.object.transform_apply(scale=True)

    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, mm(PT / 2 + 1)))
    cut = bpy.context.object
    cut.scale = (mm(well), mm(well), mm(PT + 4))
    bpy.ops.object.transform_apply(scale=True)
    bevel(cut, 2.2, segments=5)
    boolean(plate, cut)
    bevel(plate, 1.4, segments=6)
    smooth(plate)
    assign(plate, cream)

    # ---- dark tray lining the recess: floor + walls (kills white bounce) ----
    floor_z = PT - WELL_DEPTH
    tray_out = well - 0.12          # just inside the hole, avoids coplanar faces
    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, mm(PT / 2)))
    tray = bpy.context.object
    tray.name = "WellTray"
    tray.scale = (mm(tray_out), mm(tray_out), mm(PT))
    bpy.ops.object.transform_apply(scale=True)
    bpy.ops.mesh.primitive_cube_add(
        size=1, location=(0, 0, mm(floor_z + (PT - floor_z) / 2 + 1)))
    inner = bpy.context.object
    inner.scale = (mm(tray_out - 2.4), mm(tray_out - 2.4), mm(PT - floor_z + 2))
    bpy.ops.object.transform_apply(scale=True)
    boolean(tray, inner)
    assign(tray, dark)

    # ---- real KeyV2 caps, 3x3, tight ----
    src = import_cap()
    sxy = CAP / SRC_CAP
    for i, (cx, cy) in enumerate(centers):
        cap = src.copy()
        cap.data = src.data.copy()
        cap.name = f"Cap{i}"
        bpy.context.collection.objects.link(cap)
        cap.scale = (sxy, sxy, CAP_Z_SCALE)
        cap.location = (mm(cx), mm(cy), mm(floor_z + CAP_LIFT))
        smooth(cap, angle=0.5)
        assign(cap, keymat)
    bpy.data.objects.remove(src, do_unlink=True)

    # ---- studio ----
    bpy.ops.mesh.primitive_plane_add(size=3.0, location=(0, 0.5, -0.0004))
    bg = bpy.context.object
    bm = bmesh.new()
    bm.from_mesh(bg.data)
    bmesh.ops.subdivide_edges(bm, edges=bm.edges[:], cuts=24, use_grid_fill=True)
    for v in bm.verts:
        if v.co.y > 0.35:
            v.co.z += (v.co.y - 0.35) ** 2 * 1.6
    bm.to_mesh(bg.data)
    bg.data.update()
    assign(bg, satin("Backdrop", (0.62, 0.60, 0.575), rough=0.85))

    def light(name, loc, energy, size, rot):
        bpy.ops.object.light_add(type="AREA", location=loc, rotation=rot)
        L = bpy.context.object
        L.name = name
        L.data.energy = energy
        L.data.size = size

    light("Key", (mm(-250), mm(-210), mm(330)), 70, 0.75,
          (math.radians(38), 0, math.radians(-48)))
    light("Fill", (mm(320), mm(-240), mm(180)), 14, 1.2,
          (math.radians(58), 0, math.radians(52)))
    light("Rim", (mm(40), mm(300), mm(240)), 40, 0.6, (math.radians(-48), 0, 0))


def cam(loc, rot, lens, focus_d, fstop=11.0):
    bpy.ops.object.camera_add(location=loc, rotation=rot)
    c = bpy.context.object
    c.data.lens = lens
    c.data.dof.use_dof = True
    c.data.dof.focus_distance = focus_d
    c.data.dof.aperture_fstop = fstop
    bpy.context.scene.camera = c
    return c


def render(path, samples=300):
    sc = bpy.context.scene
    sc.render.engine = "CYCLES"
    try:
        prefs = bpy.context.preferences.addons["cycles"].preferences
        prefs.compute_device_type = "METAL"
        prefs.get_devices()
        for d in prefs.devices:
            d.use = True
        sc.cycles.device = "GPU"
    except Exception:
        pass
    sc.cycles.samples = samples
    sc.cycles.use_denoising = True
    sc.cycles.max_bounces = 6
    sc.cycles.diffuse_bounces = 2
    sc.render.resolution_x = 1700
    sc.render.resolution_y = 1275
    sc.render.filepath = path
    sc.view_settings.look = "AgX - Base Contrast"
    sc.view_settings.exposure = -2.25
    bpy.ops.render.render(write_still=True)


if __name__ == "__main__":
    build()
    # steeper 3/4 hero — shows cap height, taper and the dark well
    cam((mm(175), mm(-215), mm(205)), (math.radians(48), 0, math.radians(39)),
        72, 0.31, fstop=13.0)
    render(f"{OUT_DIR}/face_keys_wl_a.png")
    # near top-down graphic
    bpy.data.objects.remove(bpy.context.scene.camera, do_unlink=True)
    cam((mm(30), mm(-58), mm(275)), (math.radians(13), 0, math.radians(28)),
        60, 0.28, fstop=13.0)
    render(f"{OUT_DIR}/face_keys_wl_b.png")
